# Generated by Django 3.1.1 on 2021-02-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='lists',
        ),
        migrations.AddField(
            model_name='job',
            name='lists',
            field=models.ManyToManyField(to='lists.List'),
        ),
    ]
